p8105_hw2_dcm2192
================
Dylan Morgan
2024-10-02

``` r
library(tidyverse)
library(dplyr)
```

This file will include answers to the questions for HW 2.

## Problem 1

*Load NYC transit subway data, clean up variable names, retain only
select variables.*

``` r
nyc_transit <- 
  read_csv(file = "./data_hw2/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") |> 
  janitor::clean_names() |> 
  select(line, station_name, station_latitude, station_longitude, route1, route2, route3, route4, route5, route6, route7, route8, route9, route10, route11, entrance_type, entry, vending, ada)
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

*Convert* `entry` *variable from character to logical.*

``` r
nyc_transit$entry <- ifelse(nyc_transit$entry == "YES", TRUE, FALSE)
```

The `nyc_transit` dataset contains the variables `line`, `station_name`,
`station_latitutde`, `station_longitude`, `route1` through `route11`,
`entrance_type`, `entry`, `vending` and `ada`. Thus far, the data
cleaning process has involved using the `clean_names()` function from
the `janitor` package, which converted the variable names to snake_case
and replaced special characters if they were present in the variable
name. Other parts of the data cleaning process include using the
`select()` function to keep only the variables mentioned previously, as
well as using the `ifelse()` function to help convert the character data
type of the `entry` variable to a logical data type, converting “YES”
and “NO” to TRUE and FALSE, respectively. The `nyc_transit` dataset has
1868 rows and 19 columns. The data is relatively tidy, but there does
appear to be some redundancies in the dataset where there are multiple
rows with the same data corresponding to the same precise geographic
coordinates, so the dataset could be consolidated slightly.

*Find number of distinct subway stations.*

``` r
nyc_transit |> 
  distinct(line, station_name)
```

    ## # A tibble: 465 × 2
    ##    line     station_name            
    ##    <chr>    <chr>                   
    ##  1 4 Avenue 25th St                 
    ##  2 4 Avenue 36th St                 
    ##  3 4 Avenue 45th St                 
    ##  4 4 Avenue 53rd St                 
    ##  5 4 Avenue 59th St                 
    ##  6 4 Avenue 77th St                 
    ##  7 4 Avenue 86th St                 
    ##  8 4 Avenue 95th St                 
    ##  9 4 Avenue 9th St                  
    ## 10 4 Avenue Atlantic Av-Barclays Ctr
    ## # ℹ 455 more rows

There are 465 distinct subway stations.

*Find number of stations that are ADA compliant.*

``` r
nyc_transit |> 
  filter(ada == TRUE) |> 
  distinct(line, station_name)
```

    ## # A tibble: 84 × 2
    ##    line            station_name                  
    ##    <chr>           <chr>                         
    ##  1 4 Avenue        Atlantic Av-Barclays Ctr      
    ##  2 4 Avenue        DeKalb Av                     
    ##  3 4 Avenue        Pacific St                    
    ##  4 42nd St Shuttle Grand Central                 
    ##  5 6 Avenue        34th St                       
    ##  6 6 Avenue        47-50th Sts Rockefeller Center
    ##  7 6 Avenue        Church Av                     
    ##  8 63rd Street     21st St                       
    ##  9 63rd Street     Lexington Av                  
    ## 10 63rd Street     Roosevelt Island              
    ## # ℹ 74 more rows

There are 84 distinct stations that are ADA compliant.

*Find proportion of station entrances / exits without vending that allow
entrance.*  

Stations without vending: 99

``` r
nyc_transit |> 
  filter(vending == "NO") |> 
  distinct(line, station_name)
```

    ## # A tibble: 99 × 2
    ##    line            station_name         
    ##    <chr>           <chr>                
    ##  1 4 Avenue        53rd St              
    ##  2 4 Avenue        77th St              
    ##  3 4 Avenue        9th St               
    ##  4 4 Avenue        Bay Ridge Av         
    ##  5 42nd St Shuttle Grand Central        
    ##  6 6 Avenue        7th Av               
    ##  7 6 Avenue        Bergen St            
    ##  8 6 Avenue        Broadway-Lafayette St
    ##  9 8 Avenue        135th St             
    ## 10 8 Avenue        14th St              
    ## # ℹ 89 more rows

Stations without vending that allow entrance: 43

``` r
nyc_transit |> 
  filter(vending == "NO", entry == TRUE) |> 
  distinct(line, station_name)
```

    ## # A tibble: 43 × 2
    ##    line     station_name
    ##    <chr>    <chr>       
    ##  1 4 Avenue 9th St      
    ##  2 6 Avenue 7th Av      
    ##  3 6 Avenue Bergen St   
    ##  4 8 Avenue 135th St    
    ##  5 8 Avenue 59th St     
    ##  6 8 Avenue Spring St   
    ##  7 Brighton Av J        
    ##  8 Brighton West 8th St 
    ##  9 Broadway 23rd St     
    ## 10 Broadway 8th St      
    ## # ℹ 33 more rows

The proportion of station entrances/exits without vending that allow
entrance is 0.4343434.

*Reformat data so that route number and route name are distinct
variables. Find number of distinct stations that serve the A train. Of
the stations that serve A train, find how many are ADA compliant.*

``` r
nyc_transit |> 
  mutate(route8 = as.character(route8), 
         route9 = as.character(route9), 
         route10 = as.character(route10), 
         route11 = as.character(route11)) |> 
  pivot_longer(route1:route11, 
               names_to = "route_number", 
               values_to = "route_name") |> 
  filter(route_name == "A") |> 
  distinct(line, station_name)
```

    ## # A tibble: 60 × 2
    ##    line            station_name                 
    ##    <chr>           <chr>                        
    ##  1 42nd St Shuttle Times Square                 
    ##  2 8 Avenue        125th St                     
    ##  3 8 Avenue        145th St                     
    ##  4 8 Avenue        14th St                      
    ##  5 8 Avenue        168th St - Washington Heights
    ##  6 8 Avenue        175th St                     
    ##  7 8 Avenue        181st St                     
    ##  8 8 Avenue        190th St                     
    ##  9 8 Avenue        34th St                      
    ## 10 8 Avenue        42nd St                      
    ## # ℹ 50 more rows

There are 60 distinct stations that serve the A train.

``` r
nyc_transit |> 
  mutate(route8 = as.character(route8), 
         route9 = as.character(route9), 
         route10 = as.character(route10), 
         route11 = as.character(route11)) |> 
  pivot_longer(route1:route11, 
               names_to = "route_number", 
               values_to = "route_name") |> 
  filter(route_name == "A", ada == TRUE) |> 
  distinct(line, station_name)
```

    ## # A tibble: 17 × 2
    ##    line             station_name                 
    ##    <chr>            <chr>                        
    ##  1 8 Avenue         14th St                      
    ##  2 8 Avenue         168th St - Washington Heights
    ##  3 8 Avenue         175th St                     
    ##  4 8 Avenue         34th St                      
    ##  5 8 Avenue         42nd St                      
    ##  6 8 Avenue         59th St                      
    ##  7 8 Avenue         Inwood - 207th St            
    ##  8 8 Avenue         West 4th St                  
    ##  9 8 Avenue         World Trade Center           
    ## 10 Broadway         Times Square-42nd St         
    ## 11 Broadway-7th Ave 59th St-Columbus Circle      
    ## 12 Broadway-7th Ave Times Square                 
    ## 13 Canarsie         8th Av                       
    ## 14 Franklin         Franklin Av                  
    ## 15 Fulton           Euclid Av                    
    ## 16 Fulton           Franklin Av                  
    ## 17 Rockaway         Howard Beach

Of the stations that serve the A train, 17 are ADA compliant.

## Problem 2

*Read and clean Mr. Trash Wheel data.*

``` r
mr_trash_wheel <- readxl::read_excel("./data_hw2/202409 Trash Wheel Collection Data.xlsx", 
                                     sheet = "Mr. Trash Wheel", 
                                     range = "A2:N653") |> 
  janitor::clean_names() |> 
  mutate(sports_balls = round(sports_balls, digits = 0)) |> 
  mutate(sports_balls = as.integer(sports_balls)) |> 
  mutate(trash_wheel_name = "Mr. Trash Wheel") |> 
  mutate(year = as.numeric(year))
```

*Read and clean Professor Trash Wheel data.*

``` r
prof_trash_wheel <- readxl::read_excel("./data_hw2/202409 Trash Wheel Collection Data.xlsx",
                                       sheet = "Professor Trash Wheel", 
                                       range = "A2:M120") |> 
  janitor::clean_names() |> 
  mutate(trash_wheel_name = "Professor Trash Wheel")
```

*Read and clean Gwynnda data.*

``` r
gwynnda <- readxl::read_excel("./data_hw2/202409 Trash Wheel Collection Data.xlsx", 
                              sheet = "Gwynnda Trash Wheel", 
                              range = "A2:L265") |> 
  janitor::clean_names() |> 
  mutate(trash_wheel_name = "Gwynnda")
```

*Combine all trash wheel data into single tidy dataset.*

``` r
trash_wheel_tidy <- bind_rows(mr_trash_wheel, prof_trash_wheel, gwynnda)
```
